# Setup
title: "hyo-choi"
tagline: "공부하는 블로그"
description:
url: https://hyo-choi.github.io
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Hyojeong Choi
  url: https://hyo-choi.github.io
  email: hyochoi31@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: UA-191415773-1
